### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'fp16'

### ISSUE THREAD

**Issue by zhangbowen1999** [fast-vid2vid/fast-vid2vid#10]
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    train()
  File "train.py", line 38, in train
    models = create_model(opt,False)
  File "/home/mfw/Desktop/zbw/fast_vid2vid/fast-vid2vid-main/models/models.py", line 94, in create_model
    flowNet.initialize(opt)  
  File "/home/mfw/Desktop/zbw/fast_vid2vid/fast-vid2vid-main/models/flownet.py", line 19, in initialize
    self.flowNet = flownet2_tools.module_to_dict(flownet2_models)['FlowNet2'](fp16=opt.fp16).cuda(self.gpu_ids[0])        
TypeError: __init__() got an unexpected keyword argument 'fp16'

**Comment by zhangbowen1999** [comment]
I hope to seek help

**Comment by zhangbowen1999** [comment]
train_keypoints
train_img
how  to setting

**Comment by fast-vid2vid** [comment]
Hi @zhangbowen1999 , maybe you can remove 'fp16' first and use the new ``opt''.

**Comment by zhangbowen1999** [comment]
> Hi @zhangbowen1999 , maybe you can remove 'fp16' first and use the new ``opt''.
hello，I would like to inquire about how to install flownet2_models and can they run on the cuda11 series

**Comment by fast-vid2vid** [comment]
Hi @zhangbowen1999 , in our test environment, Flownet2_models can be run on both CUDA 10 and 11. Some errors can be solved in the original repo of flownet2.

**Comment by zhanghongyong123456** [comment]
> Hi @zhangbowen1999 , maybe you can remove 'fp16' first and use the new ``opt''.
about  train error
https://github.com/fast-vid2vid/fast-vid2vid/issues/2#issuecomment-1710183999
